development:
  adapter: postgresql
  encoding: unicode
  database: sloppin_development
  pool: 5
  username: alrick
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sloppin_test
  pool: 5
  username: alrick
  password: