Tag.delete_all
Tag.create!(:name => "Building", :description => "Can be a museum, a factory, etc.")
Tag.create!(:name => "Event", :description => "Maybe the FIFA world cup?")
Tag.create!(:name => "Exploration", :description => "Indiana Jones would use this.")
Tag.create!(:name => "Food", :description => "Can be a restaurant, a hot dog vendor, etc.")
Tag.create!(:name => "Monument", :description => "Eiffel tower and Wall of China are munuments.")
Tag.create!(:name => "Music", :description => "Can be a festival, a concert, etc.")
Tag.create!(:name => "Must", :description => "A place that you highly recommend.")
Tag.create!(:name => "Nights out", :description => "Because we're social.")
Tag.create!(:name => "Relation", :description => "That's your encounters.")
Tag.create!(:name => "Relaxation", :description => "Can be a beach, a swimming pool, etc.")
Tag.create!(:name => "Shopping", :description => "Because traveling is a good reason to spend some money.")
Tag.create!(:name => "Sport", :description => "Because travel does not necessarily rhyme with relaxation.")
Tag.create!(:name => "Transport", :description => "Can be a road trip, a plane ride, etc.")