Tag.delete_all
Tag.create!(:name => "Building", :description => "Can be a museum, a factory, etc.")
Tag.create!(:name => "Event", :description => "Maybe the FIFA world cup?")
Tag.create!(:name => "Exploration", :description => "Indiana Jones would use this.")
Tag.create!(:name => "Food", :description => "Can be a restaurant, a hot dog vendor, etc.")
Tag.create!(:name => "Monument", :description => "Eiffel tower and Wall of China are munuments.")
Tag.create!(:name => "Music", :description => "Can be a festival, a concert, etc.")
Tag.create!(:name => "Must", :description => "A place that you highly recommend.")
Tag.create!(:name => "Nights out", :description => "Because we're social.")
Tag.create!(:name => "Relation", :description => "That's your encounters.")
Tag.create!(:name => "Relaxation", :description => "Can be a beach, a swimming pool, etc.")
Tag.create!(:name => "Shopping", :description => "Because traveling is a good reason to spend some money.")
Tag.create!(:name => "Sport", :description => "Because travel does not necessarily rhyme with relaxation.")
Tag.create!(:name => "Transport", :description => "Can be a road trip, a plane ride, etc.")

Token.delete_all
Token.create!(:value => "O7hNBFthPm9JRMikUsLitQ")
Token.create!(:value => "Nxz-edvraK5PnJVC6x83Yw")
Token.create!(:value => "DpCQKrBJz4oXqEvf9CAoQA")
Token.create!(:value => "20bLFvr4zdsE8KzRw4CkQA")
Token.create!(:value => "vKDUzoCVX2Yt2EVengfoyg")
Token.create!(:value => "XJdhNraiNC4WBuOfkEax2A")
Token.create!(:value => "nvBg6J2BhKHBfYur4QT74g")
Token.create!(:value => "KPEFQZ_xPTx2OOjF2WT9ew")
Token.create!(:value => "u6Es6yGVO9m_lWEzTPxgaQ")
Token.create!(:value => "QOWkOW9eVTISStJsiw7gFw")
Token.create!(:value => "zx_lOVrZamvFhGzXoCaTlQ")
Token.create!(:value => "yqI6wGmTxYKSQRiX6rvl-A")
Token.create!(:value => "HbH8rFhPhI9kmKpNj9Vnfw")
Token.create!(:value => "VZe3gtHtpf7_Vd86BBtQtQ")
Token.create!(:value => "iRnmL4m_fEGZtQZkMJ-sWA")
Token.create!(:value => "BMmUmogZ-AGzRtVPP4Wggw")
Token.create!(:value => "a13ejh6MF3iMsp-SJ_RMYA")
Token.create!(:value => "6fA9uG0IBYBxKJ6CC6STEg")
Token.create!(:value => "x2ruW2ReTayunbZIF6xlYg")
Token.create!(:value => "JXYHynG_40pNZnYBPWdxGQ")
Token.create!(:value => "SGdBzGruPsvez7FyyyWpOQ")
Token.create!(:value => "2ys9PXVWWggSCZRr1vg81g")
Token.create!(:value => "ckq7EQr90N8Cm62ddR_rEw")
Token.create!(:value => "EVRGtrxjRiK0r6eMmYGPcQ")
Token.create!(:value => "fwIestfUrMxNm6DGER05xQ")
Token.create!(:value => "O2W008HgUxTk6vFdTKD_gw")
Token.create!(:value => "iJb4kwARP2O3S3hqgExLEQ")
Token.create!(:value => "3EkO7pivQHYTJBdHt7O6uw")