Tag.delete_all
Tag.create!(:name => "Building", :description => "Can be a museum, a factory, etc.")
Tag.create!(:name => "Event", :description => "Maybe the FIFA world cup?")
Tag.create!(:name => "Exploration", :description => "Indiana Jones would use this.")
Tag.create!(:name => "Food", :description => "Can be a restaurant, a hot dog vendor, etc.")
Tag.create!(:name => "Monument", :description => "Eiffel tower and Wall of China are munuments.")
Tag.create!(:name => "Music", :description => "Can be a festival, a concert, etc.")
Tag.create!(:name => "Must", :description => "A place that you highly recommend.")
Tag.create!(:name => "Nights out", :description => "Because we're social.")
Tag.create!(:name => "Relation", :description => "That's your encounters.")
Tag.create!(:name => "Relaxation", :description => "Can be a beach, a swimming pool, etc.")
Tag.create!(:name => "Shopping", :description => "Because traveling is a good reason to spend some money.")
Tag.create!(:name => "Sport", :description => "Because travel does not necessarily rhyme with relaxation.")
Tag.create!(:name => "Transport", :description => "Can be a road trip, a plane ride, etc.")

Token.delete_all
Token.create!(:value => "alrick.deillon@gmail.com")
Token.create!(:value => "info@3dweb.ch")
Token.create!(:value => "v.rime@curlybrackets.ch")
Token.create!(:value => "terence.alberti@gmail.com")
Token.create!(:value => "loraine.coquoz@gmail.com")
Token.create!(:value => "adrien.python@me.com")
Token.create!(:value => "gilles_angeloz@hotmail.com")
Token.create!(:value => "doriangambin@gmail.com")
Token.create!(:value => "scherwey.muriel@gmail.com")
Token.create!(:value => "lehner.benoit@gmail.com")
Token.create!(:value => "frederic.emery@hotmail.com")
Token.create!(:value => "pascal@pgraber.ch")
Token.create!(:value => "pascal.felber@unine.ch")
Token.create!(:value => "kd@tdm.ch")
Token.create!(:value => "jay@tdm.ch")
Token.create!(:value => "cd@tdm.ch")
Token.create!(:value => "burch_@hotmail.com")
Token.create!(:value => "pauline.scherwey@gmail.com")
Token.create!(:value => "nicolas.gumy@gmail.com")
Token.create!(:value => "geoffrey.papaux@gmail.com")
Token.create!(:value => "valentin.bourqui@gmail.com")
Token.create!(:value => "vgrivel@gmail.com")
Token.create!(:value => "maxime.wicht@gmail.com")
Token.create!(:value => "jonathan.sigg@gmail.com")
Token.create!(:value => "vincent.pasquier@gmail.com")
Token.create!(:value => "p.vieira@tdm.ch")