$("#pinModal .modal-body").html("<%= j(render('galleries/galleries')) %>")
$("#pinModalLabel").html("<%= j(render('users/show/pin_modal_header')) %>")
$("#pinModal .modal-footer").html("<%= j(render('users/show/pin_modal_footer')) %>")
$("#map-galleriesmodalbtn").button("toggle")
$("#pinModal").animate({ width: "1000px", marginLeft: "-500px" })
$("#pinModal").modal()